[package]
name = "opnsense-config-faker-fuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
libfuzzer-sys = "0.4"
opnsense-config-faker = { path = ".." }

# Fuzzing configuration
[profile.release]
debug = true
overflow-checks = true
lto = "fat"
codegen-units = 1
panic = "abort"

# Fuzzing targets
[[bin]]
name = "xml_parsing"
path = "fuzz_targets/xml_parsing.rs"

[[bin]]
name = "csv_parsing"
path = "fuzz_targets/csv_parsing.rs"

[[bin]]
name = "vlan_generation"
path = "fuzz_targets/vlan_generation.rs"
